### ISSUE TITLE
Can I use webRTC to send data?

### ISSUE THREAD

**Issue by JSharpClone** [IhorKlimov/Android-WebRtc#1]
Hello, your tutorial is easy to understand.
I have been looking for a webrtc tutorial for a long time.
I want to use a phone to send some data like gravity to another phone.
And then I can do something on that phone.
Is there a way to use webrtc connection to do it so that I don't need to create another connection and deal with NAT problem?
Thanks!

**Comment by IhorKlimov** [comment]
Definitely, I'll create a tutorial and a repo for it with simple server in a while!

**Comment by azzahrah** [comment]
Good... waitting simple server to testing

**Comment by IhorKlimov** [comment]
https://github.com/IhorKlimov/Android-WebRtc/blob/master/app/src/main/java/com/myhexaville/androidwebrtc/sample/SampleDataChannelActivity.java
